name: deploy api
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create zipfile
        run: "cd server && npm install && npm run build && zip -r deployx.zip *"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.}}
          aws_secret_key: ZsYrT2hlN98ftJs76jpN2mjRbaR15SdNYU7gYdzk
          application_name: nodejsserver
          environment_name: Nodejsserver-env
          version_label: ${{ github.sha }}
          region: us-west-2
          deployment_package: ./server/deployx.zip





 