name: deploy api
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create zipfile
        run: "cd server && npm install && npm run build && zip -r deploy.zip *"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: 
          aws_secret_key: 
          application_name: aws-beanstalk
          environment_name: aws-beanstalk-env
          version_label: ${{ github.sha }}
          region: us-west-2
          deployment_package: ./server/deploy.zip





 